name: Update AUR (git) Package

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Full history for version

      - name: Update PKGBUILD version
        run: |
          # Get current version
          _commit_count=$(git rev-list --count HEAD)
          _commit_hash=$(git rev-parse --short HEAD)

          echo "_commit_count=$_commit_count"
          echo "_commit_hash=$_commit_hash"
          echo "Current pkgver: "
          grep "^pkgver=" PKGBUILD

          # Format string
          new_pkgver="r${_commit_count}.${_commit_hash}"
          sed -i "s/^pkgver=.*/pkgver=$new_pkgver/" PKGBUILD

          echo "updated PKGBUILD version: "
          grep "^pkgver=" PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: void-mod-manager-git
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update AUR pacakge"
          ssh_keyscan_types: rsa,ecdsa,ed25519
